# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MedicalDB' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MedicalDB
  pod 'Fabric'
  pod 'Crashlytics'

  target 'MedicalDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
